@SchoolMaster_HostAddress = http://localhost:7001

GET {{SchoolMaster_HostAddress}}/weatherforecast/
Accept: application/json

### onboard tenant
POST {{SchoolMaster_HostAddress}}/api/onboarding/tenants
Content-Type: application/json
Accept: application/json

{
  "schoolName": "Susie Academy",
  "subdomain": "susie.academy.edu",
  "contactEmail": "hello@susie.edu",
  "adminEmail": "susanojone@gmail.com",
  "AdminFirstName":"Susan",
  "AdminLastName":"Ojone",
  "adminPassword": "SecurePassword123!"
}

### verify email
POST {{SchoolMaster_HostAddress}}/api/onboarding/verify-email
Content-Type: application/json
Accept: application/json

{
  "email": "susanojone@gmail.com",
  "otpToken": "1419"
}

### resend verification token
POST {{SchoolMaster_HostAddress}}/api/onboarding/resend-verification-token
Content-Type: application/json
Accept: application/json

{
  "email": "susanojone@gmail.com"
}

### forgot password
POST {{SchoolMaster_HostAddress}}/api/onboarding/forgot-password
Content-Type: application/json
Accept: application/json
# X-Tenant-Subdomain: susie.academy.edu

{
  "email": "susanojone@gmail.com"
}

### reset password
POST {{SchoolMaster_HostAddress}}/api/onboarding/reset-password
Content-Type: application/json
Accept: application/json
X-Tenant-Subdomain: susie.academy.edu

{
  "email": "susanojone@gmail.com",
  "otp": "0000",
  "password": "NewSecurePassword123!"
}


"email": "susanojone@gmail.com",
  "password": "NewSecurePassword123!",